name: Code Scan (Master)

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: "Build and Scan"
    runs-on: windows-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Setup Scanner Tool
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Checkout Source
      uses: actions/checkout@v2
      
    - name: Build and Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./sonar-scan.cmd
